---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: unifi-controller
  name: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 2Gi
status: {}