---

- name: Set up cluster-wide configuration.
  hosts: k3s_cluster
  gather_facts: true
  become: true

  handlers:
    - name: reboot-pi
      reboot:

  tasks:
    - name: Check if Armbian
      stat:
        path: /etc/armbian-release
      register: armbian_release

    - name: Ensure cgroups are configured correctly in cmdline.txt
      ansible.builtin.replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "cgroup_memory=1"
        - "cgroup_enable=memory"
      when: not armbian_release.stat.exists
      notify: reboot-pi

    - name: Ensure cgroups are configured correctly in armbianEnv.txt
      lineinfile:
        path: /boot/armbianEnv.txt
        regexp: '^extraargs='
        line: 'extraargs=cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
      when: armbian_release.stat.exists
      notify: reboot-pi


- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  vars:
    k3s_become: true
    k3s_etcd_datastore: true
    k3s_install_hard_links: true
  roles:
    - role: xanmanning.k3s