---

k3s_cluster:
  hosts:
    node-1:
      ansible_user: pi
      ansible_host: node1.k3s.yorgos.net.gr
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
      k3s_become: true
      ansible_ssh_extra_args: -i ~/.ssh/yorgos_home_admin

    node-2:
      ansible_user: pi
      ansible_host: node2.k3s.yorgos.net.gr
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
      k3s_become: true
      k3s_registration_address: node1.k3s.yorgos.net.gr
      ansible_ssh_extra_args: -i ~/.ssh/yorgos_home_admin

    node-3:
      ansible_user: pi
      ansible_host: node3.k3s.yorgos.net.gr
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: false
      k3s_become: true
      k3s_registration_address: node1.k3s.yorgos.net.gr
      ansible_ssh_extra_args: -i ~/.ssh/yorgos_home_admin

    node-4:
      ansible_user: k3s
      ansible_host: 192.168.100.184
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
      k3s_become: true
      k3s_registration_address: node1.k3s.yorgos.net.gr
      ansible_ssh_extra_args: -i ~/.ssh/yorgos_home_admin