# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- letsencrypt-prod.yaml
- letsencrypt-staging.yaml
- middleware.yaml

# namespace to deploy all Resources to
namespace: cert-manager

# labels added to all Resources
#commonLabels:
#  app: cert-manager

#patchesStrategicMerge:
#- increase_replicas.yaml
#- set_memory.yaml