apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mosquitto
  name: mosquitto-tcp
spec:
  ports:
  - name: tcp
    nodePort: 31883
    port: 1883
    protocol: TCP
    targetPort: mqtt
  selector:
    app.kubernetes.io/name: mosquitto
  type: NodePort
