apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: unifi-stun

spec:
  entryPoints:
    - unifi
  routes:
  - services:
    - name: unifi-controller
      port: 3478
      weight: 10