---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-persistent-storage
spec:
  storageClassName: managed-nfs-storage-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi