---
apiVersion: v1
kind: Service
metadata:
  name: piper
spec:
  selector:
    app.kubernetes.io/instance: piper-tts
    app.kubernetes.io/name: piper-tts
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10200
      targetPort: 10200