---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: cert-manager-redirect-https@kubernetescrd
spec:
  rules:
  - host: unifi.k3s.yorgos.net.gr
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: unifi-controller
              port:
                name: https-web
  tls:
    - secretName: unifi-tls
      hosts:
        - unifi.k3s.yorgos.net.gr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-inform
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: unifi.k3s.yorgos.net.gr
    http:
      paths:
        - path: /inform
          pathType: Exact
          backend:
            service:
              name: unifi-controller
              port:
                number: 8080

