---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photoprism
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - host: photoprism.k3s.yorgos.net.gr
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: photoprism
              port:
                name: http
